development:
  adapter: sqlite3
  database: db/spree_development.sqlite3
test:
  adapter:  postgresql
  encoding: unicode
  database: apartment_spree_test
  pool:     40
  username: vincentfranco
  password:
  host:     localhost
production:
  adapter: sqlite3
  database: db/spree_production.sqlite3

