

development:
  adapter: postgresql
  database: apartment_spree_spree_development
  username: postgres
  min_messages: warning

test:
  adapter: postgresql
  database: apartment_spree_spree_test
  username: postgres
  min_messages: warning

production:
  adapter: postgresql
  database: apartment_spree_spree_production
  username: postgres
  min_messages: warning


