# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c16e0d569be4c91bcfa46dc1c915ea6cd432145b9e8f93df972a926d9bb97e3d2410c1d698f7bf43e308147747bcd2fcc389ebd6e40976eb3281e9015b5fab8b

test:
  secret_key_base: 927609dc11f99ca0c86445dc018a9b84827cfc08baf16be42ad99655fd22c3693d81add6db9b6821846d7608a0366f45d539399267f2ede2efd1d31a3a6bd263

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
